name: example
description: A new Flutter project.
version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  sign_in_button:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  uses-material-design: true
